# Generated by Django 2.2.6 on 2019-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20191107_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_participacion',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='registro/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(default='comprobantes/default.png', upload_to='comprobantes/'),
        ),
    ]
