# Generated by Django 2.2.6 on 2019-11-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20191107_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Entrada')),
            ],
        ),
    ]
