# Generated by Django 2.2.6 on 2019-11-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_asientos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asientos',
            new_name='Asiento',
        ),
    ]
